package me.hunter.altguardian.api.model;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

// Import removed: java.util.Collections; // No longer needed
// Import removed: java.util.HashSet; // No longer needed
import java.util.Objects;
import java.util.Set;
import java.util.UUID;

/**
 * Represents detailed information about a player account tracked by AltGuardian.
 * This is an immutable data transfer object (DTO) used by the API.
 * <p>
 * Implemented as a Java Record (requires Java 14+).
 */
public record AccountDetails(
        @NotNull String username,
        long registrationTimestamp, // Unix timestamp (milliseconds)
        long lastLoginTimestamp,    // Unix timestamp (milliseconds)
        @Nullable UUID offlineUuidAtRegistration, // Can be null if not captured/available
        @NotNull Set<String> flags // Set of active flags - Will be made unmodifiable by Set.copyOf
) {

    /**
     * Canonical constructor for the record.
     * Ensures immutability of the flags set using Set.copyOf().
     */
    public AccountDetails(@NotNull String username,
                          long registrationTimestamp,
                          long lastLoginTimestamp,
                          @Nullable UUID offlineUuidAtRegistration,
                          @NotNull Set<String> flags) {
        // Use Objects.requireNonNull for constructor parameter validation
        this.username = Objects.requireNonNull(username, "Username cannot be null");
        this.registrationTimestamp = registrationTimestamp;
        this.lastLoginTimestamp = lastLoginTimestamp;
        this.offlineUuidAtRegistration = offlineUuidAtRegistration; // Nullable is fine

        // <<< Use Set.copyOf() for creating an immutable copy (Java 10+) >>>
        this.flags = Set.copyOf(Objects.requireNonNull(flags, "Flags set cannot be null"));
    }

    // --- Getters are automatically generated by the record ---
    // username()
    // registrationTimestamp()
    // lastLoginTimestamp()
    // offlineUuidAtRegistration()
    // flags()

    // --- equals(), hashCode(), and toString() are automatically generated ---

    // <<< Removed the commented-out equals() and hashCode() methods >>>

}