package me.hunter.altguardian.api.model;

import org.jetbrains.annotations.NotNull;

import java.util.Objects;

/**
 * Represents a record of a specific IP address used by a player account.
 * This is an immutable data transfer object (DTO) used by the API.
 * <p>
 * Implemented as a Java Record (requires Java 14+).
 */
public record IpHistoryRecord(
        @NotNull String ipAddress,
        long firstUsedTimestamp, // Unix timestamp (milliseconds)
        long lastUsedTimestamp  // Unix timestamp (milliseconds)
) {

    /**
     * Canonical constructor for the record.
     * Includes null check for ipAddress.
     */
    public IpHistoryRecord(@NotNull String ipAddress, long firstUsedTimestamp, long lastUsedTimestamp) {
        // Use Objects.requireNonNull for constructor parameter validation
        this.ipAddress = Objects.requireNonNull(ipAddress, "IP Address cannot be null");
        this.firstUsedTimestamp = firstUsedTimestamp;
        this.lastUsedTimestamp = lastUsedTimestamp;
    }

    // --- Getters are automatically generated by the record ---
    // ipAddress()
    // firstUsedTimestamp()
    // lastUsedTimestamp()

    // --- equals(), hashCode(), and toString() are automatically generated ---

    // No need to override generated methods for this simple record.
}